title = "Phorward Software Technologies"
base_url = "/"
compile_sass = true
build_search_index = false
insert_anchor_links = true
#highlight_theme = "kronuz"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_path = "phorward-logo.svg"
logo_name = "Phorward Software Technologies"
extra_menu = [
    { title = "GitHub", link = "https://github.com/phorward"}
]
